import type { Metadata } from "next";
import { Montserrat, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { RootLayoutProps } from "@/types";
import { ThemeProvider } from "@/components/providers/theme-provider";
import ClerkProviders from "@/components/providers/clerk-provider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight:['400','500', '600', '700','800','900']
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-spaceGrotesk",
  subsets: ["latin"],
  weight:['400','500', '600', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: RootLayoutProps) {
  return (
   
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.variable} ${spaceGrotesk.variable} antialiased`}
      >
         <ThemeProvider
            storageKey="pk_test_Y29uY3JldGUtY2hvdy04Ny5jbGVyay5hY2NvdW50cy5kZXYk"
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
           <ClerkProviders>
             {children}
           </ClerkProviders>
        </ThemeProvider>
      </body>
    </html>
   
  );
}
